<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

/**
 * This is the model class for table "invoice".
 *
 * @property int $id
 * @property string $subject
 * @property int $customer_id
 * @property int|null $tax
 * @property string|null $issue_date
 * @property string|null $due_date
 * @property string|null $created_at
 * @property string|null $updated_at
 *
 * @property Customer $customer
 * @property InvoiceDetail[] $invoiceDetails
 */
class Invoice extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'invoice';
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'value' => new Expression('NOW()'),
            ]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['subject', 'customer_id'], 'required'],
            [['customer_id', 'tax'], 'integer'],
            [['issue_date', 'due_date', 'created_at', 'updated_at'], 'safe'],
            [['subject'], 'string', 'max' => 255],
            [['customer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Customer::className(), 'targetAttribute' => ['customer_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'subject' => 'Subject',
            'customer_id' => 'Customer ID',
            'tax' => 'Tax',
            'issue_date' => 'Issue Date',
            'due_date' => 'Due Date',
            'created_at' => 'Created',
            'updated_at' => 'Updated',
        ];
    }

    /**
     * Gets query for [[Customer]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(Customer::className(), ['id' => 'customer_id']);
    }

    /**
     * Gets query for [[InvoiceDetails]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getInvoiceDetails()
    {
        return $this->hasMany(InvoiceDetail::className(), ['invoice_id' => 'id']);
    }

    public function beforeSave($insert)
    {
        $this->issue_date = date("Y-m-d h:i:s", strtotime($this->issue_date));
        $this->due_date = date("Y-m-d h:i:s", strtotime($this->due_date));

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
